name: Publish Docker image

on:
  schedule:
    - cron: '* * * * *'  # Запускать каждую минуту

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: littlebigchannel
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t myapp .
          docker tag myapp:latest littlebigchannel/micro:latest
          docker push littlebigchannel/micro:latest
